version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:80"
      - "4430:443"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IMCDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: